name: Terraform Workflow

on:
  push:
    branches:
      - main  

jobs:
  deploy_vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.0  

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}


    - name: Initialize Terraform
      run: terraform init

    # - name: Change to Terraform code directory
    #   run: cd /SNYK-CI-CD

    - name: Snyk Code Scanning
      run: snyk iac test --severity-threshold=critical

    - name: Apply Terraform changes
      run: terraform apply -auto-approve

    - name: Snyk Code Scanning
      run: snyk monitor

    # - name: Destroy Terraform resources
    #   run: terraform destroy -auto-approve








