name: Run Azure Login with OIDC
on: [push]

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show



# name: Deploy Azure VM

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# permissions:
#   id-token: write

# jobs:
#   deploy_vm:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Azure Login
#         uses: az login
#         with:
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#           enable-AzPSSession: true

#       - name: Azure CLI script
#         uses: azure/CLI@v1
#         with:
#           azcliversion: latest
#           inlineScript: |
#             az account show

#       - name: Install Snyk CLI
#         run: npm install -g snyk

#       - name: Authenticate Snyk
#         run: snyk auth ${{ secrets.SNYK_TOKEN }}

#       - name: terraform init
#         run: terraform init

#       - name: terraform plan
#         run: terraform plan

#       - name: Snyk Code Scanning
#         run: snyk test

#       - name: terraform apply
#         run: terraform apply -auto-approve


# #--service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}